import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Container from "./(app)/Container";
import { WebAppProvider } from "@vkruglikov/react-telegram-web-app";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<head>
				<link rel="preload" href="/images/private_bg.png" as="image" />
				<link rel="preload" href="/images/fox.svg" as="image" />
				<link rel="preload" href="/images/fox_star.svg" as="image" />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
				/>
				<Script
					strategy='beforeInteractive'
					src='https://telegram.org/js/telegram-web-app.js'
				></Script>
			</head>
			<body
				className="overflow-auto bg-[#080607]"
				// style={{
				// 	overflow: "hidden",
				// 	backgroundColor: "#080607",
				// }}
			>
				<Toaster position='top-center' />

				{children}
			</body>
		</html>
	);
}
